package server

import (
	"github.com/go-chi/chi/v5"
)

func (s *Server) routes() {
	s.mux.Get("/health", s.handleHealth)
	s.mux.Get("/readyz", s.handleReadiness)

	s.mux.Route("/api/v1", func(r chi.Router) {
		if s.enableDevAuth {
			r.Post("/auth/dev-session", s.limitHandler("auth_dev_session", 60, s.handleDevSession))
			r.Post("/dev/contact-sessions", s.limitHandler("dev_contact_session", 10, s.handleCreateDevContactSession))
		}
		r.Post("/auth/password/login", s.limitHandler("password_login", 20, s.handlePasswordLogin))
		r.Post("/auth/password", s.limitHandler("password_set", 20, s.handleSetPassword))
		r.Post("/auth/email-registration/start", s.limitHandler("email_registration_start", 20, s.handleStartEmailRegistration))
		r.Post("/auth/email-registration/confirm", s.limitHandler("email_registration_confirm", 20, s.handleConfirmEmailRegistration))
		r.Get("/auth/oauth/start", s.limitHandler("oauth_start", 20, s.handleOAuthStart))
		r.Get("/auth/oauth/callback", s.limitHandler("oauth_callback", 20, s.handleOAuthCallback))
		r.Get("/auth/session", s.handleGetSession)
		r.Post("/auth/logout", s.handleLogout)
		r.Get("/search", s.limitHandler("search", 60, s.handleSearch))
		r.Get("/me/profile", s.handleMyProfile)
		r.Patch("/me/profile", s.handleUpdateMyProfile)
		r.Post("/me/email-verification/start", s.limitHandler("email_verification_start", 20, s.handleStartEmailVerification))
		r.Post("/me/email-verification/confirm", s.limitHandler("email_verification_confirm", 20, s.handleConfirmEmailVerification))
		r.Get("/me/contact-methods", s.handleMyContactMethods)
		r.Get("/me/merchant-profile", s.handleMyMerchantProfile)
		r.Post("/me/merchant-profile", s.handleUpsertMyMerchantProfile)
		r.Patch("/me/merchant-profile", s.handleUpsertMyMerchantProfile)
		r.Get("/users/{username}/public-profile", s.handlePublicUserProfile)
		r.Get("/users/{username}/reviews", s.handlePublicUserReviews)
		r.Get("/users/{username}/disputes", s.handlePublicUserDisputes)
		r.Get("/merchant-profiles/{slug}", s.handlePublicMerchantProfile)
		r.Get("/announcements", s.handleAnnouncements)
		r.Get("/announcements/active", s.handleActiveAnnouncements)
		r.Get("/announcements/home", s.handleHomeAnnouncement)
		r.Get("/announcements/{slug}", s.handleAnnouncementDetail)

		r.Get("/product-categories", s.handleProductCategories)
		r.Get("/product-plans", s.handleProductPlans)
		r.Get("/product-plans/{id}", s.handleProductPlan)
		r.Get("/api-models", s.handleAPIModels)
		r.Get("/api-models/{id}", s.handleAPIModel)
		r.Get("/api-services", s.handlePublicAPIServices)
		r.Get("/api-services/{id}", s.handlePublicAPIService)
		r.Post("/api-services/{id}/purchase-intents", s.limitHandler("api_purchase_intent_create", 20, s.handleCreateAPIPurchaseIntent))
		r.Get("/official-prices", s.handleOfficialPrices)
		r.Get("/official-prices/{id}", s.handleOfficialPrice)
		r.Get("/demands", s.handleDemands)
		r.Post("/demands", s.handleCreateDemand)
		r.Get("/demands/{id}", s.handleDemand)
		r.Get("/carpools", s.handlePublicCarpools)
		r.Post("/carpools", s.handleCreateCarpool)
		r.Post("/carpools/publish", s.handlePublishCarpool)
		r.Get("/carpools/{id}", s.handlePublicCarpool)
		r.Patch("/carpools/{id}", s.handleUpdateCarpool)
		r.Post("/carpools/{id}/submit-review", s.handleSubmitCarpoolReview)
		r.Post("/carpools/{id}/applications", s.handleCreateCarpoolApplication)
		r.Post("/official-price-leads", s.handleSubmitOfficialPriceLead)
		r.Get("/me/official-price-leads", s.handleMyOfficialPriceLeads)
		r.Get("/me/official-price-leads/{id}", s.handleMyOfficialPriceLead)
		r.Get("/me/demands", s.handleMyDemands)
		r.Get("/me/demands/{id}", s.handleMyDemand)
		r.Post("/me/demands/{id}/close", s.handleCloseDemand)
		r.Post("/me/demands/{id}/reopen", s.handleReopenDemand)
		r.Post("/me/feedback-tickets", s.limitHandler("feedback_create", 20, s.handleCreateFeedbackTicket))
		r.Get("/me/feedback-tickets", s.handleMyFeedbackTickets)
		r.Get("/me/feedback-tickets/unread-count", s.handleMyFeedbackUnreadCount)
		r.Get("/me/feedback-tickets/{id}", s.handleMyFeedbackTicket)
		r.Post("/me/feedback-tickets/{id}/supplements", s.limitHandler("feedback_supplement", 30, s.handleAddFeedbackSupplement))
		r.Post("/me/feedback-tickets/{id}/read", s.handleMarkFeedbackRead)
		r.Get("/me/favorites", s.handleMyFavorites)
		r.Get("/me/favorites/{targetType}/{targetId}", s.handleFavoriteStatus)
		r.Put("/me/favorites/{targetType}/{targetId}", s.handleCreateFavorite)
		r.Delete("/me/favorites/{targetType}/{targetId}", s.handleDeleteFavorite)
		r.Get("/me/reviews", s.handleMyReviewCenter)
		r.Put("/me/reviews/carpool-memberships/{membershipId}", s.handleSubmitCarpoolMembershipReview)
		r.Post("/reports", s.limitHandler("report_create", 10, s.handleCreateReport))
		r.Get("/me/reports", s.handleMyReports)
		r.Post("/me/appeals", s.limitHandler("appeal_create", 10, s.handleCreateAppeal))
		r.Get("/me/appeals", s.handleMyAppeals)
		r.Get("/me/carpools", s.handleMyCarpools)
		r.Get("/me/carpool-applications", s.handleMyCarpoolApplications)
		r.Get("/me/carpool-applications/{id}", s.handleMyCarpoolApplication)
		r.Post("/me/carpool-applications/{id}/cancel", s.handleCancelCarpoolApplication)
		r.Post("/me/carpool-applications/{id}/confirm-join", s.handleBuyerConfirmCarpoolJoin)
		r.Get("/me/carpool-memberships", s.handleMyCarpoolMemberships)
		r.Post("/me/carpool-memberships/{id}/confirm-complete", s.handleBuyerConfirmCarpoolMembershipComplete)
		r.Post("/me/carpool-memberships/{id}/leave", s.handleBuyerLeaveCarpoolMembership)
		r.Get("/me/api-purchase-intents", s.handleMyAPIPurchaseIntents)
		r.Get("/me/api-purchase-intents/{id}", s.limitHandler("api_purchase_intent_contact_read", 60, s.handleMyAPIPurchaseIntent))
		r.Post("/me/api-purchase-intents/{id}/cancel", s.handleCancelAPIPurchaseIntent)
		r.Post("/me/api-purchase-intents/{id}/orders", s.handleCreateAPIOrder)
		r.Get("/me/api-orders", s.handleMyAPIOrders)
		r.Get("/me/api-orders/{id}", s.handleMyAPIOrder)
		r.Post("/me/api-orders/{id}/payment-instructions", s.limitHandler("api_order_payment_instructions", 60, s.handleReadAPIOrderPaymentInstructions))
		r.Post("/me/api-orders/{id}/submit-payment", s.handleSubmitAPIOrderPayment)
		r.Post("/me/api-orders/{id}/cancel", s.handleCancelAPIOrder)
		r.Post("/me/api-orders/{id}/confirm-complete", s.handleConfirmAPIOrderComplete)
		r.Post("/me/api-orders/{id}/dispute", s.handleOpenAPIOrderDispute)
		r.Get("/me/notifications", s.handleMyNotifications)
		r.Get("/me/notifications/unread-count", s.handleNotificationUnreadCount)
		r.Post("/me/notifications/{id}/read", s.handleMarkNotificationRead)
		r.Post("/me/notifications/read-all", s.handleMarkAllNotificationsRead)
		r.Get("/me/announcements/unread-count", s.handleAnnouncementUnreadCount)
		r.Get("/me/announcements/important-unread-count", s.handleImportantAnnouncementUnreadCount)
		r.Post("/me/announcements/{id}/seen", s.handleMarkAnnouncementSeen)
		r.Post("/me/announcements/{id}/read", s.handleMarkAnnouncementRead)
		r.Post("/me/announcements/{id}/dismiss", s.handleDismissAnnouncement)

		r.Get("/owner/carpool-applications", s.handleOwnerCarpoolApplications)
		r.Get("/owner/carpool-applications/{id}", s.handleOwnerCarpoolApplication)
		r.Post("/owner/carpool-applications/{id}/accept", s.handleAcceptCarpoolApplication)
		r.Post("/owner/carpool-applications/{id}/reject", s.handleRejectCarpoolApplication)
		r.Post("/owner/carpool-applications/{id}/withdraw-acceptance", s.handleWithdrawCarpoolAcceptance)
		r.Post("/owner/carpool-applications/{id}/confirm-join", s.handleOwnerConfirmCarpoolJoin)
		r.Get("/owner/carpool-memberships", s.handleOwnerCarpoolMemberships)
		r.Post("/owner/carpool-memberships/{id}/confirm-complete", s.handleOwnerConfirmCarpoolMembershipComplete)
		r.Post("/owner/carpool-memberships/{id}/remove", s.handleOwnerRemoveCarpoolMembership)
		r.Get("/owner/api-services", s.handleOwnerAPIServices)
		r.Get("/owner/api-services/{id}", s.handleOwnerAPIService)
		r.Post("/owner/api-services", s.handleCreateAPIService)
		r.Patch("/owner/api-services/{id}", s.handleUpdateAPIService)
		r.Post("/owner/api-services/{id}/submit-review", s.handleSubmitAPIServiceReview)
		r.Post("/owner/api-services/{id}/publish", s.handlePublishAPIService)
		r.Post("/owner/api-services/{id}/pause", s.handlePauseAPIService)
		r.Post("/owner/api-services/{id}/resume", s.handleResumeAPIService)
		r.Post("/owner/api-services/{id}/start-revision", s.handleStartAPIServiceRevision)
		r.Patch("/owner/api-services/{id}/order-settings", s.handleUpdateAPIServiceOrderSettings)
		r.Get("/owner/api-purchase-intents", s.handleOwnerAPIPurchaseIntents)
		r.Get("/owner/api-purchase-intents/{id}", s.limitHandler("api_purchase_intent_contact_read", 60, s.handleOwnerAPIPurchaseIntent))
		r.Post("/owner/api-purchase-intents/{id}/mark-contacted", s.handleMarkAPIPurchaseIntentContacted)
		r.Post("/owner/api-purchase-intents/{id}/close", s.handleCloseAPIPurchaseIntent)
		r.Get("/owner/api-orders", s.handleOwnerAPIOrders)
		r.Get("/owner/api-orders/{id}", s.handleOwnerAPIOrder)
		r.Post("/owner/api-orders/{id}/confirm-payment", s.handleConfirmAPIOrderPayment)
		r.Post("/owner/api-orders/{id}/submit-delivery", s.handleSubmitAPIOrderDelivery)

		r.Get("/admin/official-price-leads", s.handleAdminOfficialPriceLeads)
		r.Get("/admin/official-price-leads/{id}", s.handleAdminOfficialPriceLead)
		r.Post("/admin/official-price-leads/{id}/approve", s.handleApproveOfficialPriceLead)
		r.Post("/admin/official-price-leads/{id}/reject", s.handleRejectOfficialPriceLead)
		r.Post("/admin/official-price-leads/{id}/request-changes", s.handleRequestChangesOfficialPriceLead)
		r.Get("/admin/demands", s.handleAdminDemands)
		r.Get("/admin/demands/{id}", s.handleAdminDemand)
		r.Post("/admin/demands/{id}/approve", s.handleApproveDemand)
		r.Post("/admin/demands/{id}/request-changes", s.handleRequestChangesDemand)
		r.Post("/admin/demands/{id}/reject", s.handleRejectDemand)
		r.Post("/admin/demands/{id}/take-down", s.handleTakeDownDemand)
		r.Post("/admin/demands/{id}/restore", s.handleRestoreDemand)
		r.Get("/admin/feedback-tickets", s.handleAdminFeedbackTickets)
		r.Get("/admin/feedback-tickets/{id}", s.handleAdminFeedbackTicket)
		r.Post("/admin/feedback-tickets/{id}/handle", s.handleAdminFeedbackHandle)
		r.Get("/admin/carpools", s.handleAdminCarpools)
		r.Get("/admin/carpools/{id}", s.handleAdminCarpool)
		r.Post("/admin/carpools/{id}/approve", s.handleApproveCarpool)
		r.Post("/admin/carpools/{id}/reject", s.handleRejectCarpool)
		r.Post("/admin/carpools/{id}/request-changes", s.handleRequestChangesCarpool)
		r.Post("/admin/carpools/{id}/pause", s.handlePauseCarpool)
		r.Post("/admin/carpools/{id}/restore", s.handleRestoreCarpool)
		r.Get("/admin/api-services", s.handleAdminAPIServices)
		r.Get("/admin/api-services/{id}", s.handleAdminAPIService)
		r.Post("/admin/api-services/{id}/approve", s.handleApproveAPIService)
		r.Post("/admin/api-services/{id}/request-changes", s.handleRequestChangesAPIService)
		r.Post("/admin/api-services/{id}/reject", s.handleRejectAPIService)
		r.Post("/admin/api-services/{id}/suspend", s.handleSuspendAPIService)
		r.Post("/admin/api-services/{id}/restore", s.handleRestoreAPIService)
		r.Post("/admin/api-services/{id}/remove", s.handleRemoveAPIService)
		r.Get("/admin/api-purchase-intents", s.handleAdminAPIPurchaseIntents)
		r.Get("/admin/api-purchase-intents/{id}", s.handleAdminAPIPurchaseIntent)
		r.Get("/admin/product-categories", s.handleAdminProductCategories)
		r.Post("/admin/product-categories", s.handleCreateProductCategory)
		r.Get("/admin/product-categories/{id}", s.handleAdminProductCategory)
		r.Patch("/admin/product-categories/{id}", s.handleUpdateProductCategory)
		r.Post("/admin/product-categories/{id}/activate", s.handleActivateProductCategory)
		r.Post("/admin/product-categories/{id}/deactivate", s.handleDeactivateProductCategory)
		r.Get("/admin/product-plans", s.handleAdminProductPlans)
		r.Post("/admin/product-plans", s.handleCreateProductPlan)
		r.Get("/admin/product-plans/{id}", s.handleAdminProductPlan)
		r.Patch("/admin/product-plans/{id}", s.handleUpdateProductPlan)
		r.Post("/admin/product-plans/{id}/activate", s.handleActivateProductPlan)
		r.Post("/admin/product-plans/{id}/deactivate", s.handleDeactivateProductPlan)
		r.Get("/admin/api-model-providers", s.handleAdminAPIModelProviders)
		r.Post("/admin/api-model-providers", s.handleCreateAPIModelProvider)
		r.Get("/admin/api-model-providers/{id}", s.handleAdminAPIModelProvider)
		r.Patch("/admin/api-model-providers/{id}", s.handleUpdateAPIModelProvider)
		r.Post("/admin/api-model-providers/{id}/activate", s.handleActivateAPIModelProvider)
		r.Post("/admin/api-model-providers/{id}/deactivate", s.handleDeactivateAPIModelProvider)
		r.Get("/admin/api-models", s.handleAdminAPIModels)
		r.Post("/admin/api-models", s.handleCreateAPIModel)
		r.Get("/admin/api-models/{id}", s.handleAdminAPIModel)
		r.Patch("/admin/api-models/{id}", s.handleUpdateAPIModel)
		r.Post("/admin/api-models/{id}/activate", s.handleActivateAPIModel)
		r.Post("/admin/api-models/{id}/deactivate", s.handleDeactivateAPIModel)
		r.Get("/admin/model-audit/targets", s.handleAdminModelAuditTargets)
		r.Post("/admin/model-audit/targets", s.handleCreateModelAuditTarget)
		r.Get("/admin/model-audit/targets/{id}", s.handleAdminModelAuditTarget)
		r.Patch("/admin/model-audit/targets/{id}", s.handleUpdateModelAuditTarget)
		r.Delete("/admin/model-audit/targets/{id}", s.handleDeleteModelAuditTarget)
		r.Get("/admin/model-audit/baselines", s.handleAdminModelAuditBaselines)
		r.Post("/admin/model-audit/baselines", s.handleCreateModelAuditBaseline)
		r.Get("/admin/model-audit/baselines/{id}", s.handleAdminModelAuditBaseline)
		r.Get("/admin/model-audit/runs", s.handleAdminModelAuditRuns)
		r.Post("/admin/model-audit/runs", s.handleCreateModelAuditRun)
		r.Get("/admin/model-audit/runs/{id}", s.handleAdminModelAuditRun)
		r.Post("/admin/model-audit/runs/{id}/cancel", s.handleCancelModelAuditRun)
		r.Get("/admin/model-audit/runs/{id}/report", s.handleAdminModelAuditReport)
		r.Get("/admin/model-audit/scheduled-monitors", s.handleAdminModelAuditMonitors)
		r.Post("/admin/model-audit/scheduled-monitors", s.handleCreateModelAuditMonitor)
		r.Get("/admin/reports", s.handleAdminReports)
		r.Get("/admin/reports/{id}", s.handleAdminReport)
		r.Post("/admin/reports/{id}/triage", s.handleTriageReport)
		r.Post("/admin/reports/{id}/request-info", s.handleRequestReportInfo)
		r.Post("/admin/reports/{id}/reject", s.handleRejectReport)
		r.Post("/admin/reports/{id}/open-dispute", s.handleOpenReportDispute)
		r.Post("/admin/reports/{id}/close", s.handleCloseReport)
		r.Get("/admin/disputes", s.handleAdminDisputes)
		r.Get("/admin/disputes/{id}", s.handleAdminDispute)
		r.Post("/admin/disputes/{id}/request-info", s.handleRequestDisputeInfo)
		r.Post("/admin/disputes/{id}/resolve", s.handleResolveDispute)
		r.Post("/admin/disputes/{id}/close", s.handleCloseDispute)
		r.Get("/admin/appeals", s.handleAdminAppeals)
		r.Get("/admin/appeals/{id}", s.handleAdminAppeal)
		r.Post("/admin/appeals/{id}/approve", s.handleApproveAppeal)
		r.Post("/admin/appeals/{id}/reject", s.handleRejectAppeal)
		r.Get("/admin/announcements", s.handleAdminAnnouncements)
		r.Post("/admin/announcements", s.handleCreateAnnouncement)
		r.Get("/admin/announcements/{id}", s.handleAdminAnnouncement)
		r.Patch("/admin/announcements/{id}", s.handleUpdateAnnouncement)
		r.Post("/admin/announcements/{id}/publish", s.handlePublishAnnouncement)
		r.Post("/admin/announcements/{id}/offline", s.handleOfflineAnnouncement)
		r.Post("/admin/announcements/{id}/duplicate", s.handleDuplicateAnnouncement)
		r.Get("/admin/announcement-audit-logs", s.handleAnnouncementAuditLogs)

		r.Post("/contact-methods", s.handleCreateContactMethod)
		r.Patch("/contact-methods/{id}", s.handleUpdateContactMethod)
		r.Delete("/contact-methods/{id}", s.handleDeleteContactMethod)
		r.Post("/contact-methods/{id}/set-default", s.handleSetDefaultContactMethod)
		r.Post("/contact-methods/{id}/verify", s.handleVerifyContactMethod)
		r.Get("/contact-sessions/{id}/contacts", s.limitHandler("contact_read", 60, s.handleReadContactSession))
	})
}
