package server

import (
	"net/http"

	"c2c-market/backend/internal/module/apiorder"
	"c2c-market/backend/internal/module/catalog"

	"github.com/go-chi/chi/v5"
)

func registerCatalogLifecycleRoutes(r chi.Router, basePath, resourceType string, s *Server) {
	actions := []string{
		catalog.LifecycleActionDeprecate,
		catalog.LifecycleActionBlock,
		catalog.LifecycleActionReactivate,
		catalog.LifecycleActionUnblock,
	}
	for _, action := range actions {
		action := action
		r.Post(basePath+"/"+action, func(w http.ResponseWriter, request *http.Request) {
			s.handleCatalogLifecycle(w, request, resourceType, action)
		})
	}
}

func (s *Server) routes() {
	if s.metrics != nil {
		s.mux.Use(s.metrics.Instrument)
	}
	s.mux.Get("/health", s.handleHealth)
	s.mux.Get("/readyz", s.handleReadiness)
	s.mux.Get("/version", s.handleVersion)
	s.mux.Get("/metrics", s.handleMetrics)

	s.mux.Route("/api/v1", func(r chi.Router) {
		r.Get("/announcements/public-active", s.handlePublicActiveAnnouncements)
		if s.enableDevAuth {
			r.Post("/auth/dev-session", s.limitHandler("auth_dev_session", 60, s.handleDevSession))
			r.Post("/auth/dev-persona-session", s.limitHandler("auth_dev_persona_session", 60, s.handleDevPersonaSession))
			r.Post("/dev/contact-sessions", s.limitHandler("dev_contact_session", 10, s.handleCreateDevContactSession))
		}
		r.Post("/auth/password/login", s.limitPolicy(passwordLoginRateLimit, s.handlePasswordLogin))
		r.Post("/auth/password-reset/start", s.limitPolicy(passwordResetStartRateLimit, s.handleStartPasswordReset))
		r.Post("/auth/password-reset/confirm", s.limitPolicy(passwordResetConfirmRateLimit, s.handleConfirmPasswordReset))
		r.Post("/auth/password/reauthenticate", s.limitHandler("password_reauthenticate", 20, s.handlePasswordReauthenticate))
		r.Post("/auth/password", s.limitHandler("password_set", 20, s.handleSetPassword))
		r.Get("/auth/email-registration/config", s.handleEmailRegistrationConfig)
		r.Get("/auth/username-availability", s.limitHandler("auth_username_availability", 60, s.handleUsernameAvailability))
		r.Post("/auth/email-registration/start", s.limitPolicy(emailRegistrationStartRateLimit, s.handleStartEmailRegistration))
		r.Post("/auth/email-registration/confirm", s.limitPolicy(emailRegistrationConfirmRateLimit, s.handleConfirmEmailRegistration))
		r.Get("/auth/oauth/start", s.limitPolicy(oauthStartRateLimit, s.handleOAuthStart))
		r.Get("/auth/account-appeal/start", s.limitPolicy(accountAppealStartRateLimit, s.handleAccountAppealOAuthStart))
		r.Get("/auth/oauth/callback", s.limitPolicy(oauthCallbackRateLimit, s.handleOAuthCallback))
		r.Get("/account-appeal/session", s.limitPolicy(accountAppealSessionRateLimit, s.handleGetAccountAppealSession))
		r.Post("/account-appeal/appeals", s.limitPolicy(accountAppealCreateRateLimit, s.handleCreateAccountGovernanceAppeal))
		r.Get("/auth/session", s.handleGetSession)
		r.Post("/auth/logout", s.handleLogout)
		r.Get("/auth/restricted-business/session", s.handleGetRestrictedBusinessSession)
		r.Post("/auth/restricted-business/logout", s.handleRestrictedBusinessLogout)
		r.Get("/search", s.limitHandler("search", 60, s.handleSearch))
		r.Get("/me/profile", s.handleMyProfile)
		r.Get("/me/account-governance/business-center", s.handleAccountGovernanceBusinessCenter)
		r.Get("/me/api-payment-settings", s.handleMyAPIAccountPaymentSettings)
		r.Put("/me/api-payment-settings", s.handleUpdateMyAPIAccountPaymentSettings)
		r.Get("/me/navigation-badges", s.handleNavigationBadges)
		r.Get("/me/events", s.handleMyEvents)
		r.Patch("/me/profile", s.handleUpdateMyProfile)
		r.Post("/me/email-verification/start", s.limitPolicy(emailVerificationStartRateLimit, s.handleStartEmailVerification))
		r.Post("/me/email-verification/confirm", s.limitPolicy(emailVerificationConfirmRateLimit, s.handleConfirmEmailVerification))
		r.Get("/me/contact-methods", s.handleMyContactMethods)
		r.Get("/me/merchant-profile", s.handleMyMerchantProfile)
		r.Post("/me/merchant-profile", s.handleUpsertMyMerchantProfile)
		r.Patch("/me/merchant-profile", s.handleUpsertMyMerchantProfile)
		r.Get("/users/{username}/public-profile", s.handlePublicUserProfile)
		r.Get("/users/{username}/reputation", s.handlePublicUserReputation)
		r.Get("/users/{username}/reviews", s.handlePublicUserReviews)
		r.Get("/users/{username}/disputes", s.handlePublicUserDisputes)
		r.Get("/merchant-profiles/{slug}", s.handlePublicMerchantProfile)
		r.Get("/announcements", s.handleAnnouncements)
		r.Get("/announcements/active", s.handleActiveAnnouncements)
		r.Get("/announcements/home", s.handleHomeAnnouncement)
		r.Get("/announcements/{slug}", s.handleAnnouncementDetail)

		r.Get("/product-categories", s.handleProductCategories)
		r.Get("/product-plans", s.handleProductPlans)
		r.Get("/product-plans/{id}", s.handleProductPlan)
		r.Get("/api-models", s.handleAPIModels)
		r.Get("/api-models/{id}", s.handleAPIModel)
		r.Get("/api-services", s.handlePublicAPIServices)
		r.Get("/api-services/filter-options", s.handlePublicAPIPackageFilterOptions)
		r.Get("/api-service-promotions", s.handlePublicAPIPromotions)
		r.Get("/promotion-rewards/public-config", s.handlePromotionRewardPublicConfig)
		r.Get("/api-services/{id}", s.handlePublicAPIService)
		r.Get("/tools/api-model-tester/order-sources", s.handleAPIModelTesterOrderSources)
		r.Post("/tools/api-model-tester/discover", s.handleAPIModelTesterDiscover)
		r.Post("/tools/api-model-tester/test", s.handleAPIModelTesterTest)
		r.Post("/api-services/{id}/purchase-intents", s.limitPolicy(apiPurchaseIntentRateLimit, s.handleCreateAPIPurchaseIntent))
		r.Get("/api-quota-sale-slots", s.handleAPIQuotaSystemSaleSlots)
		r.Get("/api-quota-offers", s.handlePublicAPIQuotaOffers)
		r.Get("/api-quota-offers/{id}", s.handlePublicAPIQuotaOffer)
		r.Post("/api-quota-offers/{id}/orders", s.limitPolicy(apiQuotaOrderRateLimit, s.handleCreateAPIQuotaOrder))
		r.Get("/official-prices", s.handleOfficialPrices)
		r.Get("/official-prices/{id}", s.handleOfficialPrice)
		r.Get("/carpools", s.handlePublicCarpools)
		r.Post("/carpools", s.handleCreateCarpool)
		r.Post("/carpools/publish", s.handlePublishCarpool)
		r.Get("/carpools/{id}", s.handlePublicCarpool)
		r.Get("/carpools/{id}/eligibility", s.handleCarpoolApplicationEligibility)
		r.Patch("/carpools/{id}", s.handleUpdateCarpool)
		r.Post("/carpools/{id}/submit-review", s.handleSubmitCarpoolReview)
		r.Post("/carpools/{id}/applications", s.limitPolicy(carpoolApplicationRateLimit, s.handleCreateCarpoolApplication))
		r.Post("/official-price-leads", s.handleSubmitOfficialPriceLead)
		r.Get("/me/official-price-leads", s.handleMyOfficialPriceLeads)
		r.Get("/me/official-price-leads/{id}", s.handleMyOfficialPriceLead)
		r.Post("/me/feedback-tickets", s.limitHandler("feedback_create", 20, s.handleCreateFeedbackTicket))
		r.Get("/me/feedback-tickets", s.handleMyFeedbackTickets)
		r.Get("/me/feedback-tickets/unread-count", s.handleMyFeedbackUnreadCount)
		r.Get("/me/feedback-tickets/{id}", s.handleMyFeedbackTicket)
		r.Post("/me/feedback-tickets/{id}/supplements", s.limitHandler("feedback_supplement", 30, s.handleAddFeedbackSupplement))
		r.Post("/me/feedback-tickets/{id}/read", s.handleMarkFeedbackRead)
		r.Get("/me/favorites", s.handleMyFavorites)
		r.Get("/me/favorites/{targetType}/{targetId}", s.handleFavoriteStatus)
		r.Put("/me/favorites/{targetType}/{targetId}", s.handleCreateFavorite)
		r.Delete("/me/favorites/{targetType}/{targetId}", s.handleDeleteFavorite)
		r.Get("/me/reviews", s.handleMyReviewCenter)
		r.Get("/me/reputation", s.handleMyReputation)
		r.Get("/me/referral", s.handleMyReferralSummary)
		r.Get("/me/promotion-coupons", s.handleMyPromotionCoupons)
		r.Post("/me/promotion-coupons/{id}/apply", s.handleApplyPromotionCoupon)
		r.Post("/me/transactions/{type}/{id}/review", s.handleCreateTransactionReview)
		r.Put("/me/transactions/{type}/{id}/review", s.handleEditTransactionReview)
		r.Post("/reports", s.limitPolicy(reportCreateRateLimit, s.handleCreateReport))
		r.Get("/me/reports", s.handleMyReports)
		r.Post("/me/reports/{id}/supplements", s.limitPolicy(reportSupplementRateLimit, s.handleSubmitReportSupplement))
		r.Get("/me/disputes", s.handleMyDisputes)
		r.Get("/me/disputes/{id}", s.handleMyDispute)
		r.Get("/me/dispute-evidence/{id}/content", s.handleMyDisputeEvidenceContent)
		r.Post("/me/disputes/{id}/seller-decision", s.handleSellerDisputeDecision)
		r.Post("/me/disputes/{id}/platform-intervention", s.handleRequestDisputePlatformIntervention)
		r.Post("/me/disputes/{id}/withdraw", s.handleWithdrawDispute)
		r.Post("/me/disputes/{id}/remedy/claim", s.handleClaimDisputeRemedy)
		r.Post("/me/disputes/{id}/remedy/confirm", s.handleConfirmDisputeRemedy)
		r.Post("/me/disputes/{id}/remedy/contest", s.handleContestDisputeRemedy)
		r.Post("/me/disputes/{id}/supplements", s.limitPolicy(reportSupplementRateLimit, s.handleSubmitDisputeSupplement))
		r.Post("/me/appeals", s.limitPolicy(appealCreateRateLimit, s.handleCreateAppeal))
		r.Get("/me/appeals", s.handleMyAppeals)
		r.Get("/me/carpools", s.handleMyCarpools)
		r.Get("/me/carpools/{id}", s.handleMyCarpool)
		r.Post("/me/carpools/{id}/stop-recruiting", s.handleStopCarpoolRecruiting)
		r.Post("/me/carpools/{id}/resume-recruiting", s.handleResumeCarpoolRecruiting)
		r.Get("/me/carpool-applications", s.handleMyCarpoolApplications)
		r.Get("/me/carpool-applications/{id}", s.handleMyCarpoolApplication)
		r.Post("/me/carpool-applications/{id}/confirm-conditions", s.handleConfirmCarpoolApplicationConditions)
		r.Post("/me/carpool-applications/{id}/cancel", s.handleCancelCarpoolApplication)
		r.Get("/me/carpool-memberships", s.handleMyCarpoolMemberships)
		r.Post("/me/carpool-memberships/{id}/leave", s.handleBuyerLeaveCarpoolMembership)
		r.Get("/me/api-purchase-intents", s.handleMyAPIPurchaseIntents)
		r.Get("/me/api-purchase-intents/{id}", s.limitHandler("api_purchase_intent_contact_read", 60, s.handleMyAPIPurchaseIntent))
		r.Post("/me/api-purchase-intents/{id}/cancel", s.handleCancelAPIPurchaseIntent)
		r.Post("/me/api-purchase-intents/{id}/orders", s.limitPolicy(apiOrderRateLimit, s.handleCreateAPIOrder))
		r.Get("/me/api-orders", s.handleMyAPIOrders)
		r.Get("/me/api-orders/{id}", s.handleMyAPIOrder)
		r.Post("/me/api-orders/{id}/payment-instructions", s.limitHandler("api_order_payment_instructions", 60, s.handleReadAPIOrderPaymentInstructions))
		r.Post("/me/api-orders/{id}/submit-payment", s.handleSubmitAPIOrderPayment)
		r.Post("/me/api-orders/{id}/cancel", s.handleCancelAPIOrder)
		r.Post("/me/api-orders/{id}/confirm-complete", s.handleConfirmAPIOrderComplete)
		r.Post("/me/api-orders/{id}/dispute", s.handleOpenAPIOrderDispute)
		r.Post("/me/api-orders/{id}/dispute-evidence", s.handleUploadAPIOrderDisputeEvidence)
		r.Post("/me/api-orders/{id}/report-late-payment", s.handleReportLateAPIOrderPayment)
		r.Get("/me/notifications", s.handleMyNotifications)
		r.Get("/me/notifications/unread-count", s.handleNotificationUnreadCount)
		r.Post("/me/notifications/{id}/read", s.handleMarkNotificationRead)
		r.Post("/me/notifications/read-all", s.handleMarkAllNotificationsRead)
		r.Get("/me/announcements/unread-count", s.handleAnnouncementUnreadCount)
		r.Get("/me/announcements/important-unread-count", s.handleImportantAnnouncementUnreadCount)
		r.Post("/me/announcements/{id}/seen", s.handleMarkAnnouncementSeen)
		r.Post("/me/announcements/{id}/read", s.handleMarkAnnouncementRead)
		r.Post("/me/announcements/{id}/dismiss", s.handleDismissAnnouncement)
		r.Post("/me/announcements/{id}/acknowledge", s.handleAcknowledgeAnnouncement)

		r.Get("/owner/carpool-applications", s.handleOwnerCarpoolApplications)
		r.Get("/owner/carpool-applications/{id}", s.handleOwnerCarpoolApplication)
		r.Post("/owner/carpool-applications/{id}/accept", s.handleAcceptCarpoolApplication)
		r.Post("/owner/carpool-applications/{id}/reject", s.handleRejectCarpoolApplication)
		r.Get("/owner/carpool-memberships", s.handleOwnerCarpoolMemberships)
		r.Post("/owner/carpool-memberships/{id}/remove", s.handleOwnerRemoveCarpoolMembership)
		r.Patch("/owner/carpool-memberships/{id}/note", s.handleOwnerUpdateCarpoolMembershipNote)
		r.Get("/owner/api-services", s.handleOwnerAPIServices)
		r.Get("/owner/api-services/{id}", s.handleOwnerAPIService)
		r.Get("/owner/api-probe-connections", s.handleOwnerAPIProbeConnections)
		r.Post("/owner/api-probe-connections/preflight", s.handlePreflightOwnerAPIProbeConnection)
		r.Post("/owner/api-probe-connections", s.handleCreateOwnerAPIProbeConnection)
		r.Get("/owner/api-probe-connections/{id}", s.handleOwnerAPIProbeConnection)
		r.Put("/owner/api-probe-connections/{id}", s.handleUpdateOwnerAPIProbeConnection)
		r.Delete("/owner/api-probe-connections/{id}", s.handleDeleteOwnerAPIProbeConnection)
		r.Post("/owner/api-probe-connections/{id}/verify", s.handleVerifyOwnerAPIProbeConnection)
		r.Post("/owner/api-probe-connections/{id}/preflight", s.handlePreflightExistingOwnerAPIProbeConnection)
		r.Post("/owner/api-services", s.handleCreateAPIService)
		r.Patch("/owner/api-services/{id}", s.handleUpdateAPIService)
		r.Patch("/owner/api-services/{id}/probe-connection", s.handleUpdateAPIServiceProbeConnection)
		r.Post("/owner/api-services/{id}/submit-review", s.handleSubmitAPIServiceReview)
		r.Post("/owner/api-services/{id}/publish", s.handlePublishAPIService)
		r.Post("/owner/api-services/{id}/pause", s.handlePauseAPIService)
		r.Post("/owner/api-services/{id}/resume", s.handleResumeAPIService)
		r.Post("/owner/api-services/{id}/start-revision", s.handleStartAPIServiceRevision)
		r.Patch("/owner/api-services/{id}/order-settings", s.handleUpdateAPIServiceOrderSettings)
		r.Get("/owner/api-services/{id}/quota-batches", s.handleOwnerAPIQuotaBatches)
		r.Post("/owner/api-services/{id}/quota-batches", s.handleCreateAPIQuotaBatch)
		r.Post("/owner/api-services/{id}/quota-rush-offers", s.handleCreateAPIQuotaRushOffer)
		r.Get("/owner/api-quota-batches/{id}/offers", s.handleOwnerAPIQuotaOffers)
		r.Post("/owner/api-quota-batches/{id}/offers", s.handleCreateAPIQuotaOffer)
		r.Get("/owner/api-quota-batches/{id}/rounds", s.handleOwnerAPIQuotaRounds)
		r.Post("/owner/api-quota-batches/{id}/rounds", s.handleCreateAPIQuotaRound)
		r.Post("/owner/api-quota-rounds/{id}/confirm-fulfillment", s.handleConfirmAPIQuotaRoundFulfillment)
		r.Post("/owner/api-quota-batches/{id}/publish", func(w http.ResponseWriter, r *http.Request) {
			s.handleAPIQuotaBatchAction(w, r, "publish")
		})
		r.Post("/owner/api-quota-batches/{id}/pause", func(w http.ResponseWriter, r *http.Request) {
			s.handleAPIQuotaBatchAction(w, r, "pause")
		})
		r.Post("/owner/api-quota-batches/{id}/resume", func(w http.ResponseWriter, r *http.Request) {
			s.handleAPIQuotaBatchAction(w, r, "resume")
		})
		r.Post("/owner/api-quota-batches/{id}/archive", func(w http.ResponseWriter, r *http.Request) {
			s.handleAPIQuotaBatchAction(w, r, "archive")
		})
		r.Post("/owner/api-quota-offers/{id}/credentials/import", s.handleImportAPIQuotaCredentials)
		r.Get("/owner/api-quota-offers/{id}/credentials/summary", s.handleAPIQuotaCredentialSummary)
		r.Get("/owner/api-purchase-intents", s.handleOwnerAPIPurchaseIntents)
		r.Get("/owner/api-purchase-intents/{id}", s.limitHandler("api_purchase_intent_contact_read", 60, s.handleOwnerAPIPurchaseIntent))
		r.Post("/owner/api-purchase-intents/{id}/mark-contacted", s.handleMarkAPIPurchaseIntentContacted)
		r.Post("/owner/api-purchase-intents/{id}/close", s.handleCloseAPIPurchaseIntent)
		r.Get("/owner/api-orders", s.handleOwnerAPIOrders)
		r.Get("/owner/api-orders/commerce-status", s.handleSellerCommerceStatus)
		r.Get("/owner/api-orders/{id}", s.handleOwnerAPIOrder)
		r.Post("/owner/api-orders/{id}/confirm-payment", s.handleConfirmAPIOrderPayment)
		r.Post("/owner/api-orders/{id}/report-payment-issue", s.handleReportAPIOrderPaymentIssue)
		r.Post("/owner/api-orders/{id}/submit-delivery", s.handleSubmitAPIOrderDelivery)
		r.Post("/owner/api-orders/{id}/resolve-late-payment", s.handleResolveLateAPIOrderPayment)

		r.Get("/admin/official-price-leads", s.handleAdminOfficialPriceLeads)
		r.Get("/admin/official-price-leads/{id}", s.handleAdminOfficialPriceLead)
		r.Post("/admin/official-price-leads/{id}/approve", s.handleApproveOfficialPriceLead)
		r.Post("/admin/official-price-leads/{id}/reject", s.handleRejectOfficialPriceLead)
		r.Post("/admin/official-price-leads/{id}/request-changes", s.handleRequestChangesOfficialPriceLead)
		r.Get("/admin/official-price-records", s.handleAdminOfficialPriceRecords)
		r.Post("/admin/official-price-records", s.handleCreateAdminOfficialPriceRecord)
		r.Get("/admin/official-price-records/{id}", s.handleAdminOfficialPriceRecord)
		r.Put("/admin/official-price-records/{id}", s.handleUpdateAdminOfficialPriceRecord)
		r.Post("/admin/official-price-records/{id}/take-down", s.handleTakeDownAdminOfficialPriceRecord)
		r.Get("/admin/feedback-tickets", s.handleAdminFeedbackTickets)
		r.Get("/admin/feedback-tickets/{id}", s.handleAdminFeedbackTicket)
		r.Post("/admin/feedback-tickets/{id}/handle", s.handleAdminFeedbackHandle)
		r.Get("/admin/carpools", s.handleAdminCarpools)
		r.Get("/admin/carpools/{id}", s.handleAdminCarpool)
		r.Post("/admin/carpools/{id}/approve", s.handleApproveCarpool)
		r.Post("/admin/carpools/{id}/reject", s.handleRejectCarpool)
		r.Post("/admin/carpools/{id}/request-changes", s.handleRequestChangesCarpool)
		r.Post("/admin/carpools/{id}/pause", s.handlePauseCarpool)
		r.Post("/admin/carpools/{id}/restore", s.handleRestoreCarpool)
		r.Get("/admin/users", s.handleAdminUsers)
		r.Get("/admin/audit-logs", s.handleAdminOperationAuditLogs)
		r.Get("/admin/student-registration", s.handleAdminStudentRegistration)
		r.Patch("/admin/student-registration", s.handleUpdateAdminStudentRegistration)
		r.Get("/admin/student-institution-domains", s.handleAdminStudentInstitutionDomains)
		r.Post("/admin/student-institution-domains", s.handleCreateAdminStudentInstitutionDomain)
		r.Patch("/admin/student-institution-domains/{id}", s.handleUpdateAdminStudentInstitutionDomain)
		r.Get("/admin/growth-overview", s.handleAdminGrowthOverview)
		r.Get("/admin/promotion-reward-campaign", s.handleAdminPromotionRewardCampaign)
		r.Patch("/admin/promotion-reward-campaign", s.handleUpdateAdminPromotionRewardCampaign)
		r.Get("/admin/referrals", s.handleAdminReferrals)
		r.Post("/admin/referrals/{id}/revoke", s.handleRevokeAdminReferral)
		r.Get("/admin/promotion-coupons", s.handleAdminPromotionCoupons)
		r.Post("/admin/promotion-coupons/grant", s.handleGrantAdminPromotionCoupon)
		r.Post("/admin/promotion-coupons/{id}/revoke", s.handleRevokeAdminPromotionCoupon)
		r.Get("/admin/users/{id}", s.handleAdminUser)
		r.Get("/admin/users/{id}/community-identities", s.handleAdminCommunityIdentities)
		r.Post("/admin/users/{id}/community-identities", s.handleGrantAdminCommunityIdentity)
		r.Post("/admin/users/{id}/community-identities/{identityType}/revoke", s.handleRevokeAdminCommunityIdentity)
		r.Post("/admin/users/{id}/status", s.handleUpdateAdminUserStatus)
		r.Post("/admin/users/{id}/admin-permission", s.handleUpdateAdminUserPermission)
		r.Get("/admin/api-services", s.handleAdminAPIServices)
		r.Get("/admin/api-service-promotions", s.handleAdminAPIPromotions)
		r.Get("/admin/api-service-promotions/availability", s.handleAPIPromotionAvailability)
		r.Post("/admin/api-service-promotions", s.handleCreateAPIPromotion)
		r.Post("/admin/api-service-promotions/{id}/stop", s.handleStopAPIPromotion)
		r.Get("/admin/api-services/{id}", s.handleAdminAPIService)
		r.Post("/admin/api-services/{id}/approve", s.handleApproveAPIService)
		r.Post("/admin/api-services/{id}/request-changes", s.handleRequestChangesAPIService)
		r.Post("/admin/api-services/{id}/reject", s.handleRejectAPIService)
		r.Post("/admin/api-services/{id}/suspend", s.handleSuspendAPIService)
		r.Post("/admin/api-services/{id}/restore", s.handleRestoreAPIService)
		r.Post("/admin/api-services/{id}/remove", s.handleRemoveAPIService)
		r.Get("/admin/api-purchase-intents", s.handleAdminAPIPurchaseIntents)
		r.Get("/admin/api-purchase-intents/{id}", s.handleAdminAPIPurchaseIntent)
		r.Get("/admin/api-orders", s.handleAdminAPIOrders)
		r.Get("/admin/api-orders/{id}", s.handleAdminAPIOrder)
		r.Post("/admin/api-orders/{id}/catalog-risk-hold/restore", func(w http.ResponseWriter, r *http.Request) {
			s.handleResolveAPIOrderCatalogRiskHold(w, r, apiorder.CatalogRiskHoldRestored)
		})
		r.Post("/admin/api-orders/{id}/catalog-risk-hold/refund-pending", func(w http.ResponseWriter, r *http.Request) {
			s.handleResolveAPIOrderCatalogRiskHold(w, r, apiorder.CatalogRiskHoldRefundPending)
		})
		r.Post("/admin/api-orders/{id}/catalog-risk-hold/open-dispute", func(w http.ResponseWriter, r *http.Request) {
			s.handleResolveAPIOrderCatalogRiskHold(w, r, apiorder.CatalogRiskHoldDisputeOpened)
		})
		r.Get("/admin/product-categories", s.handleAdminProductCategories)
		r.Post("/admin/product-categories", s.handleCreateProductCategory)
		r.Get("/admin/product-categories/{id}", s.handleAdminProductCategory)
		r.Patch("/admin/product-categories/{id}", s.handleUpdateProductCategory)
		registerCatalogLifecycleRoutes(r, "/admin/product-categories/{id}", catalog.ResourceProductCategory, s)
		r.Get("/admin/product-plans", s.handleAdminProductPlans)
		r.Post("/admin/product-plans", s.handleCreateProductPlan)
		r.Get("/admin/product-plans/{id}", s.handleAdminProductPlan)
		r.Patch("/admin/product-plans/{id}", s.handleUpdateProductPlan)
		registerCatalogLifecycleRoutes(r, "/admin/product-plans/{id}", catalog.ResourceProductPlan, s)
		r.Get("/admin/api-model-providers", s.handleAdminAPIModelProviders)
		r.Post("/admin/api-model-providers", s.handleCreateAPIModelProvider)
		r.Get("/admin/api-model-providers/{id}", s.handleAdminAPIModelProvider)
		r.Patch("/admin/api-model-providers/{id}", s.handleUpdateAPIModelProvider)
		registerCatalogLifecycleRoutes(r, "/admin/api-model-providers/{id}", catalog.ResourceAPIProvider, s)
		r.Get("/admin/api-models", s.handleAdminAPIModels)
		r.Get("/admin/api-health/latency-calibration", s.handleAdminAPIProbeLatencyCalibration)
		r.Get("/admin/api-health/latency-rules", s.handleAdminAPIProbeLatencyRules)
		r.Post("/admin/api-health/latency-rules/preview", s.handlePreviewAdminAPIProbeLatencyRule)
		r.Post("/admin/api-health/latency-rules", s.handlePublishAdminAPIProbeLatencyRule)
		r.Post("/admin/api-models", s.handleCreateAPIModel)
		r.Post("/admin/api-models/models-dev/preview", s.handlePreviewAPIModelSync)
		r.Post("/admin/api-models/models-dev/apply", s.handleApplyAPIModelSync)
		r.Get("/admin/api-models/{id}", s.handleAdminAPIModel)
		r.Patch("/admin/api-models/{id}", s.handleUpdateAPIModel)
		registerCatalogLifecycleRoutes(r, "/admin/api-models/{id}", catalog.ResourceAPIModel, s)
		r.Get("/admin/model-audit/targets", s.handleAdminModelAuditTargets)
		r.Post("/admin/model-audit/targets", s.handleCreateModelAuditTarget)
		r.Get("/admin/model-audit/targets/{id}", s.handleAdminModelAuditTarget)
		r.Patch("/admin/model-audit/targets/{id}", s.handleUpdateModelAuditTarget)
		r.Delete("/admin/model-audit/targets/{id}", s.handleDeleteModelAuditTarget)
		r.Get("/admin/model-audit/baselines", s.handleAdminModelAuditBaselines)
		r.Post("/admin/model-audit/baselines", s.handleCreateModelAuditBaseline)
		r.Get("/admin/model-audit/baselines/{id}", s.handleAdminModelAuditBaseline)
		r.Get("/admin/model-audit/runs", s.handleAdminModelAuditRuns)
		r.Post("/admin/model-audit/runs", s.limitPolicy(modelAuditRunRateLimit, s.handleCreateModelAuditRun))
		r.Get("/admin/model-audit/runs/{id}", s.handleAdminModelAuditRun)
		r.Post("/admin/model-audit/runs/{id}/cancel", s.handleCancelModelAuditRun)
		r.Get("/admin/model-audit/runs/{id}/report", s.handleAdminModelAuditReport)
		r.Get("/admin/model-audit/scheduled-monitors", s.handleAdminModelAuditMonitors)
		r.Post("/admin/model-audit/scheduled-monitors", s.handleCreateModelAuditMonitor)
		r.Post("/admin/reviews/{id}/remove", s.handleRemoveTransactionReview)
		r.Get("/admin/reports", s.handleAdminReports)
		r.Get("/admin/reports/{id}", s.handleAdminReport)
		r.Post("/admin/reports/{id}/triage", s.handleTriageReport)
		r.Post("/admin/reports/{id}/request-info", s.handleRequestReportInfo)
		r.Post("/admin/reports/{id}/reject", s.handleRejectReport)
		r.Post("/admin/reports/{id}/open-dispute", s.handleOpenReportDispute)
		r.Post("/admin/reports/{id}/close", s.handleCloseReport)
		r.Get("/admin/disputes", s.handleAdminDisputes)
		r.Get("/admin/disputes/{id}", s.handleAdminDispute)
		r.Post("/admin/disputes/{id}/request-info", s.handleRequestDisputeInfo)
		r.Post("/admin/disputes/{id}/resolve", s.handleResolveDispute)
		r.Post("/admin/disputes/{id}/close", s.handleCloseDispute)
		r.Post("/admin/disputes/{id}/remedy/confirm-lateness", s.handleConfirmDisputeRemedyLateness)
		r.Post("/admin/disputes/{id}/remedy/excuse-lateness", s.handleExcuseDisputeRemedyLateness)
		r.Post("/admin/disputes/{id}/reputation-outcome", s.handleCreateDisputeReputationOutcome)
		r.Get("/admin/disputes/{id}/sanction-recommendation", s.handleAPIOrderSanctionRecommendation)
		r.Post("/admin/disputes/{id}/sanction", s.handleApplyAPIOrderSanction)
		r.Get("/admin/dispute-evidence/{id}/content", s.handleAdminDisputeEvidenceContent)
		r.Post("/admin/dispute-evidence/{id}/quarantine", s.handleAdminQuarantineDisputeEvidence)
		r.Post("/admin/users/{id}/reputation-restrictions", s.handleCreateUserReputationRestriction)
		r.Get("/admin/users/{id}/reputation", s.handleAdminUserReputation)
		r.Post("/admin/users/{id}/reputation/recalculate", s.handleAdminRecalculateUserReputation)
		r.Post("/admin/reputation/recalculate", s.handleAdminRecalculateAllReputation)
		r.Get("/admin/source-author-verifications/{resourceType}/{resourceId}", s.handleAdminSourceAuthorVerification)
		r.Put("/admin/source-author-verifications/{resourceType}/{resourceId}", s.handleAdminUpdateSourceAuthorVerification)
		r.Post("/admin/reputation-restrictions/{id}/revoke", s.handleRevokeUserReputationRestriction)
		r.Get("/admin/appeals", s.handleAdminAppeals)
		r.Get("/admin/appeals/{id}", s.handleAdminAppeal)
		r.Post("/admin/appeals/{id}/approve", s.handleApproveAppeal)
		r.Post("/admin/appeals/{id}/reject", s.handleRejectAppeal)
		r.Get("/admin/announcements", s.handleAdminAnnouncements)
		r.Post("/admin/announcements", s.handleCreateAnnouncement)
		r.Get("/admin/announcements/{id}", s.handleAdminAnnouncement)
		r.Patch("/admin/announcements/{id}", s.handleUpdateAnnouncement)
		r.Post("/admin/announcements/{id}/publish", s.handlePublishAnnouncement)
		r.Post("/admin/announcements/{id}/offline", s.handleOfflineAnnouncement)
		r.Post("/admin/announcements/{id}/duplicate", s.handleDuplicateAnnouncement)
		r.Get("/admin/announcement-audit-logs", s.handleAnnouncementAuditLogs)

		r.Post("/contact-methods", s.handleCreateContactMethod)
		r.Patch("/contact-methods/{id}", s.handleUpdateContactMethod)
		r.Delete("/contact-methods/{id}", s.handleDeleteContactMethod)
		r.Post("/contact-methods/{id}/set-default", s.handleSetDefaultContactMethod)
		r.Post("/contact-methods/{id}/email-verification/start", s.limitPolicy(emailVerificationStartRateLimit, s.handleStartContactEmailVerification))
		r.Post("/contact-methods/{id}/email-verification/confirm", s.limitPolicy(emailVerificationConfirmRateLimit, s.handleConfirmContactEmailVerification))
		r.Get("/contact-sessions/{id}/contacts", s.limitPolicy(contactReadRateLimit, s.handleReadContactSession))
		r.Get("/reputation/rules", s.handleReputationRules)
	})
}
