-- No-op.
--
-- The project is pre-launch, and the report/dispute target contract is now
-- defined directly in 000022_reports_disputes_appeals.up.sql for fresh schema
-- creation. Keep this migration number reserved so existing development
-- histories remain ordered without introducing old/new compatibility logic.
