-- No-op.
--
-- 000028 is reserved only for migration ordering. The target type contract is
-- owned by the clean pre-launch 000022 schema, so there is no separate
-- compatibility constraint to roll back here.
