import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

function source(path: string) {
  return readFileSync(new URL(path, import.meta.url), 'utf8')
}

const healthPanel = source('../../components/api-market/ApiServiceHealthPanel.vue')
const healthStrip = source('../../components/api-market/ApiHealth24HourStrip.vue')
const tooltipContent = source('../../components/ui/tooltip/TooltipContent.vue')
const connectionPage = source('../../pages/MyApiProbeConnectionsPage.vue')
const ownerPage = source('../../pages/MyApiServiceDetailPage.vue')
const publishSection = source('../../components/api-service-publish/ProbeConnectionSection.vue')
const router = source('../../router.ts')
const appShell = source('../../components/layout/AppShell.vue')
const adminShell = source('../../components/layout/AdminShell.vue')
const query = source('../../queries/useApiHealthQueries.ts')
const backend = source('../apiHealthBackend.ts')
const adminCalibrationPage = source('../../pages/AdminApiHealthCalibrationPage.vue')
const adminQuery = source('../../queries/useAdminApiHealthQueries.ts')

describe('共享探针连接前端边界', () => {
  it('公共健康展示真实模型的 24 小时稳定性与首字速度', () => {
    expect(healthStrip).toContain('Array.from({ length: 24 }')
    expect(healthPanel).toContain('真实模型探针')
    expect(healthStrip).toContain('稳定性')
    expect(healthStrip).toContain('平均首字')
    expect(healthStrip).toContain('aria-label="近 24 小时真实模型探针状态"')
    expect(healthPanel).toContain("transportSecurity === 'insecure_http'")
    expect(healthPanel).toContain('HTTP 未加密')
    expect(healthStrip).toContain('summary.probeModel')
    expect(healthStrip).toContain('summary.p50TtftMs')
    expect(healthStrip).toContain('summary.p95TtftMs')
    expect(healthPanel).toContain("from '@/components/ui/tooltip'")
    expect(healthPanel).toContain('<TooltipProvider :delay-duration="150">')
    expect(healthPanel).toContain('<TooltipTrigger as-child>')
    expect(healthPanel).toContain('<TooltipContent')
    expect(tooltipContent).toContain('<TooltipArrow')
    expect(healthPanel).toContain('aria-label="查看探针统计详情"')
    expect(healthPanel).toContain('align="center"')
    expect(healthPanel).toContain('overflow-visible p-0')
    expect(healthPanel).toContain('var(--reka-tooltip-content-available-height)')
    expect(healthPanel).toContain('overflow-y-auto overscroll-contain')
    expect(healthPanel).not.toContain('align="start"')
    expect(healthPanel).not.toContain('@pointerenter="showDetails"')
    expect(healthPanel).not.toContain('@pointerleave="hideDetails"')
    expect(healthPanel).toContain('@click="toggleDetails"')
    expect(healthPanel).toContain('@escape-key-down="closeDetails"')
    expect(healthPanel).toContain('@pointer-down-outside="closeDetailsFromOutside"')
    expect(healthPanel).toContain('summary.p50TtftMs')
    expect(healthPanel).toContain('summary.p95TtftMs')
    expect(healthPanel).toContain('预计日费用')
  })

  it('连接管理集中处理复用、写入专用 Key 和 HTTP 主动确认', () => {
    expect(connectionPage).toContain('PageTitle title="探针连接"')
    expect(connectionPage.match(/<template #action>/g)).toHaveLength(2)
    expect(connectionPage).toContain('type="password"')
    expect(connectionPage).toContain('autocomplete="new-password"')
    expect(connectionPage).toContain('留空则使用当前 Key')
    expect(connectionPage).toContain('已有相同 Base URL 的连接')
    expect(connectionPage).toContain('>复用</Button>')
    expect(connectionPage).toContain('仍使用独立 Key 创建连接')
    expect(connectionPage).toContain('确认使用未加密 HTTP')
    expect(connectionPage).toContain('每五分钟一次；同一连接绑定多项服务也只请求一次。')
    expect(connectionPage).not.toContain('DNS TXT')
    expect(connectionPage).not.toContain('HTTP challenge')
  })

  it('服务发布选择 ready 连接，详情页支持改绑和解绑', () => {
    expect(publishSection).toContain("verificationStatus === 'verified'")
    expect(publishSection).toContain('管理连接')
    expect(publishSection).toContain('新建连接')
    expect(ownerPage).toContain('useUpdateApiServiceProbeConnectionMutation')
    expect(ownerPage).toContain('探针连接已改绑')
    expect(ownerPage).toContain("probeConnectionId: ''")
    expect(ownerPage).toContain('已有订单不受影响')
  })

  it('Owner mutation 使用 If-Match/幂等键并失效连接和服务查询', () => {
    expect(backend).toContain("{ method: 'PUT', ifMatch: input.version }")
    expect(backend).toContain("{ method: 'DELETE', ifMatch: input.version }")
    expect(backend).toContain("idempotencyPrefix: 'api-probe-connection-verify'")
    expect(query).toContain('apiHealthQueryKeys.all')
    expect(query).toContain("queryKey: ['api-services']")
  })

  it('独立 Owner 路由与导航存在，管理员审批入口已删除', () => {
    expect(router).toContain("path: '/my/api-probe-connections'")
    expect(router).not.toContain("path: '/admin/api-health-probes'")
    expect(appShell).toContain("{ label: '探针连接', to: '/my/api-probe-connections'")
    expect(adminShell).not.toContain('API 探针授权')
    expect(adminShell).toContain("to: '/admin/api-health'")
  })

  it('管理员校准页坚持 7 日与 5 连接门槛，并显式预览后发布固定阈值', () => {
    expect(adminCalibrationPage).toContain('完整自然日')
    expect(adminCalibrationPage).toContain('独立连接')
    expect(adminCalibrationPage).toContain('P50')
    expect(adminCalibrationPage).toContain('P95')
    expect(adminCalibrationPage).toContain('P99')
    expect(adminCalibrationPage).toContain("calibration?.ready ? '可发布' : '继续观测'")
    expect(adminCalibrationPage).toContain('预计慢响应黄色')
    expect(adminCalibrationPage).toContain('新规则只影响后续样本')
    expect(backend).toContain("'/api/v1/admin/api-health/latency-rules/preview'")
    expect(backend).toContain("idempotencyPrefix: 'api-probe-latency-rule-publish'")
		expect(adminQuery).toContain('adminApiHealthKeys.calibration')
  })
})
