import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

function source(path: string) {
  return readFileSync(new URL(path, import.meta.url), 'utf8')
}

const home = source('../../pages/HomePage.vue')
const homeMarketSnapshot = source('../../components/market/HomeMarketSnapshot.vue')
const search = source('../../pages/SearchPage.vue')
const login = source('../../pages/LoginPage.vue')
const officialPrices = source('../../pages/OfficialPricesPage.vue')
const officialDetail = source('../../pages/OfficialPriceDetailPage.vue')
const carpools = source('../../pages/CarpoolsPage.vue')
const carpoolDetail = source('../../pages/CarpoolDetailPage.vue')
const carpoolPublish = source('../../pages/CarpoolPublishPage.vue')
const apiMarket = source('../../pages/ApiMarketPage.vue')
const apiPurchasePanel = source('../../components/api-service-detail/ApiPurchasePanel.vue')
const apiPublish = source('../../pages/ApiServicePublishPage.vue')
const rides = source('../../pages/MyRidesPage.vue')
const rideDetail = source('../../pages/CarpoolApplicationDetailPage.vue')
const orders = source('../../pages/MyApiOrdersPage.vue')
const orderDetail = source('../../pages/ApiPurchaseOrderDetailPage.vue')
const publicUser = source('../../pages/PublicUserPage.vue')
const router = source('../../router.ts')
const routeSeo = source('../../seo/routeSeo.ts')
const nuxtConfig = source('../../../nuxt.config.ts')
const sitemapSource = source('../../../server/api/__sitemap__/urls.ts')
const robotsSource = source('../../../server/routes/robots.txt.ts')

describe('公开市场与交易页面一致性', () => {
  it('让首页成为市场入口而不是运营看板', () => {
    expect(home).toContain('发现车源、API 服务与官网价格')
    expect(home).not.toContain('home-market-stats')
    expect(home).toContain('home-entry-card')
    expect(home).toContain('不代收、不托管资金')
    expect(home).toContain('<HomeMarketSnapshot')
    expect(homeMarketSnapshot).toContain('市场新上架')
    expect(homeMarketSnapshot).toContain('<h3 id="home-carpool-snapshot-title">可申请车源</h3>')
    expect(homeMarketSnapshot).toContain('<h3 id="home-api-snapshot-title">可购买 API 服务</h3>')
    expect(home).not.toContain('TabsTrigger')
    expect(home).not.toContain('求车')
    expect(home).not.toContain('homeMarketTabStorageKey')
    expect(home).not.toContain('window.localStorage')
    expect(home).toContain('tradableCarpools.length')
    expect(home).toContain('tradableCarpools.value.slice(0, 3)')
    expect(home).toContain('orderableApiServices.value.slice(0, 3)')
    expect(home).toContain('const hasMarketData = computed(() => data.value !== undefined)')
    expect(home).toContain('<section class="home-market-entries" aria-label="市场入口" :aria-busy="isLoading">')
    expect(homeMarketSnapshot).toContain('<CarFront v-else aria-hidden="true" />')
    expect(homeMarketSnapshot).toContain('role="link"')
    expect(homeMarketSnapshot).toContain('@keydown.enter="openMarketRecord')
    expect(home).toContain('isCurrentTradable(item)')
    expect(homeMarketSnapshot).toContain('`/carpools/${item.id}`')
    expect(homeMarketSnapshot).toContain('`/api-market/${item.id}`')
    expect(router).not.toContain("path: '/demands")
    expect(router).not.toContain("path: '/my/demands")
    expect(router).not.toContain("['demands'")
    expect(routeSeo).not.toContain('/demands')
    expect(routeSeo).not.toContain('求车需求')
    expect([nuxtConfig, sitemapSource, robotsSource].join('\n')).not.toContain('/demands')
    expect(home).not.toContain('home-reference-aside')
    expect(home).not.toContain('home-hero-visual')
    expect(home).not.toContain('home-module-action')
    expect(home).not.toContain('官网价格参考')
    expect(home).not.toContain('完整价格表')
    expect(home).not.toContain('HomeTrendChart')
    expect(home).not.toContain('社区行情总览')
  })

  it('为搜索、登录和官网价格提供明确状态与边界', () => {
    expect(search).toContain('<SkeletonTable')
    expect(search).toContain('热门拼车')
    expect(login).toContain('if (session.value) await router.replace(returnTo.value)')
    expect(login.match(/<h1\b/g)).toHaveLength(1)
    expect(login).toContain('src="/c2cmarket-icon-512.png?v=20260806-deep-violet"')
    expect(officialPrices).not.toContain('official-price-category-tabs')
    expect(officialPrices).toContain('const isRealBackend = shouldUseRealBackend()')
    expect(officialPrices).toContain('v-if="!isRealBackend" class="official-price-status-filter')
    expect(officialPrices).toContain('role="link"')
    expect(officialDetail).toContain('此价格仅供参考，不等于市场交易价格')
    expect(officialDetail).toContain('税费口径')
  })

  it('让拼车保留整行导航并为额度包提供明确购买操作', () => {
    expect(carpools).toContain('carpool-reference-top')
    expect(carpools).toContain('carpool-catalog-panel')
    expect(carpools).not.toContain('关于当前筛选')
    expect(carpools).not.toContain('<dt>当前筛选</dt>')
    expect(carpools).toContain('@keydown.enter="openCarpool')
    expect(carpools).not.toContain('carpool-view-button')
    expect(apiMarket).toContain('限时额度包')
    expect(apiMarket).toContain('@purchase="purchaseOffer"')
    expect(apiMarket).toContain('<ApiQuotaOfferCard')
    expect(apiMarket).not.toContain('<Dialog')
    expect(apiMarket).not.toContain('api-market-intent-button')
  })

  it('让详情行动卡只有一个权威主操作并保留次级动作', () => {
    expect(carpoolDetail).toContain('lg:sticky lg:top-16')
    expect(carpoolDetail).toContain('申请上车')
    expect(carpoolDetail).toContain('分享')
    expect(apiPurchasePanel).toContain('创建订单并查看付款方式')
    expect(apiPurchasePanel).toContain('平台记录状态但不代收、不托管资金')
    expect(apiPurchasePanel).toContain('付款窗口')
  })

  it('保护发布页未保存内容并保持真实预览', () => {
    expect(carpoolPublish).toContain('useUnsavedChangesGuard')
    expect(carpoolPublish).toContain('CarpoolPublishPreview')
    expect(apiPublish).toContain('useUnsavedChangesGuard')
    expect(apiPublish).toContain('ApiServicePublishPreview')
  })

  it('统一申请和订单的短编号、本地时间、快照与下一动作', () => {
    expect(rides).toContain('<ShortId')
    expect(rides).toContain('<LocalTime')
    expect(rideDetail).toContain('ride-order-stepper')
    expect(rideDetail).toContain('ride-order-action-card')
    expect(rideDetail).toContain('申请快照')
    expect(orders).toContain('<ShortId')
    expect(orders).toContain('<LocalTime')
    expect(orderDetail).toContain('<Stepper')
    expect(orderDetail).toContain('当前可执行操作')
  })

  it('公开用户页只展示有来源的公开活动并统一全空状态', () => {
    expect(publicUser).toContain('hasPublicActivity')
    expect(publicUser).toContain('暂无公开业务记录')
    expect(publicUser).toContain('不展示任何联系方式')
  })
})
